# Generated by Django 6.0.3 on 2026-04-14 21:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='roles',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_rol', models.CharField(max_length=64)),
                ('descripcion', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='usuarios',
            fields=[
                ('created_at', models.DateField(auto_created=True)),
                ('id_usuario', models.IntegerField(auto_created=True, primary_key=True, serialize=False)),
                ('nombre_completo', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('contrasena', models.CharField(max_length=128)),
                ('activo', models.BooleanField()),
                ('rol', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rol', to='escuela.roles')),
            ],
        ),
    ]
