# Generated by Django 6.0.4 on 2026-04-22 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='agenda_tareas',
            name='nota',
            field=models.FloatField(default=0),
            preserve_default=False,
        ),
    ]
