# Generated by Django 6.0.3 on 2026-04-14 21:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='agenda_tareas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=200)),
                ('fecha_entrega', models.DateField()),
            ],
        ),
        migrations.CreateModel(
            name='cursos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_curso', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='grado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('grade', models.CharField(max_length=64)),
                ('seccion', models.CharField(max_length=5)),
            ],
        ),
        migrations.CreateModel(
            name='alumnos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_alumno', to='escuela.usuarios')),
                ('grado_seccion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grado', to='escuela.grado')),
            ],
        ),
        migrations.CreateModel(
            name='calificaciones',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nota', models.FloatField()),
                ('trimestre', models.IntegerField()),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_alumnos', to='escuela.alumnos')),
                ('id_tarea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_tarea', to='escuela.agenda_tareas')),
            ],
        ),
        migrations.AddField(
            model_name='agenda_tareas',
            name='id_curso',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='agenda_curso', to='escuela.cursos'),
        ),
        migrations.CreateModel(
            name='logs_auditoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('evento', models.CharField(max_length=100)),
                ('detalles', models.CharField(max_length=300)),
                ('ip_address', models.GenericIPAddressField()),
                ('created_at', models.DateField(auto_now=True)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='logs', to='escuela.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='maestros',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('especialidad', models.CharField(max_length=100)),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_maestro', to='escuela.usuarios')),
            ],
        ),
        migrations.AddField(
            model_name='cursos',
            name='id_maestro',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='curso_maestro', to='escuela.maestros'),
        ),
        migrations.CreateModel(
            name='asistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True)),
                ('estado', models.BooleanField()),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencia_alumnos', to='escuela.alumnos')),
                ('id_maestro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='asistencia_maestro', to='escuela.maestros')),
            ],
        ),
        migrations.CreateModel(
            name='padres_tutores',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telefono_emergencia', models.IntegerField()),
                ('id_usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usuario_padre', to='escuela.usuarios')),
            ],
        ),
        migrations.CreateModel(
            name='pagos',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('monto', models.FloatField()),
                ('fecha_pago', models.DateField(auto_now=True)),
                ('estado', models.BooleanField()),
                ('id_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pago_padre', to='escuela.padres_tutores')),
            ],
        ),
        migrations.CreateModel(
            name='relacion_familia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('id_alumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacion_alumnos', to='escuela.alumnos')),
                ('id_padre', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relacion_padre', to='escuela.padres_tutores')),
            ],
        ),
    ]
