# Generated by Django 6.0.4 on 2026-04-25 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0003_mensaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='subject',
            field=models.CharField(default='a', max_length=50),
            preserve_default=False,
        ),
    ]
