# Generated by Django 6.0.4 on 2026-04-25 23:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0004_mensaje_subject'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensaje',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
