# Generated by Django 6.0.4 on 2026-04-29 21:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0005_mensaje_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='calificaciones',
            name='id_curso',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='calificacion_curso', to='escuela.cursos'),
            preserve_default=False,
        ),
    ]
