# Generated by Django 6.0.4 on 2026-05-07 03:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('escuela', '0006_calificaciones_id_curso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pagos',
            name='fecha_pago',
            field=models.DateField(),
        ),
    ]
